#!/usr/bin/env python3
"""Generate the PapaBench simulation stimulus (papabench_stim.svh).

The environment module (hw/rtl/papabench_env.sv) replays these tables from
the clock only, so every run sees the same inputs at the same cycles.

Radio (FBW, PPM on gp_i[0] of GPIO bank 0): PPM_FRAMES frames of 9 pulse
widths in us, in PPM order (radio.h: 0 throttle, 1 roll, 2 pitch, 3 yaw,
4 mode, 5 gain1, 6 gain2, 7 LLS, 8 calib), 25 ms each. FBW averages the mode stick over
AVERAGING_PERIOD = 10 frames (ppm.c) and the Autopilot reads it from FBW
over SPI, so the mode changes on those 250 ms boundaries:
  frames  0-9   mode 1100 us: MANUAL (FBW and Autopilot), throttle 1600 us
  frames 10-19  mode 1600 us: FBW AUTO, Autopilot AUTO1, full throttle
  frames 20-    mode 1900 us: FBW AUTO, Autopilot AUTO2, full throttle
                (2100 us > GAZ_THRESHOLD_TAKEOFF: AUTO2 launches)
Roll stick sweeps 1300..1900 us (16-frame triangle). After the last frame
the environment replays from PPM_LOOP, so the aircraft stays in AUTO2.

GPS (Autopilot, UBX on the UART): GPS_EPOCHS epochs at 4 Hz, each the
burst NAV-POSUTM, NAV-STATUS, NAV-VELNED (the three messages
autopilot/gps_ubx.c decodes). The aircraft flies a circle of radius
CIRCLE_R m around (CIRCLE_E, CIRCLE_N) relative to NAV_UTM_EAST0/NORTH0
(flight_plan.h) at SPEED m/s and ALT m, with a 3D fix.

Usage: gen_stimulus.py <output.svh>
"""

import math
import struct
import sys

# ------------------------------------------------------------------ radio
PPM_AVERAGING = 10              # fly_by_wire/ppm.c AVERAGING_PERIOD
PPM_LOOP = 2 * PPM_AVERAGING    # first AUTO2 frame, replayed from here
PPM_FRAMES = PPM_LOOP + 16      # one roll sweep in the replayed part
PPM_CHANNELS = 9


def ppm_frame(n):
    tri = n % 16
    tri = tri if tri < 8 else 16 - tri          # 0..8..0
    roll = 1300 + 75 * tri                       # 1300..1900 us
    if n < PPM_AVERAGING:
        mode, throttle = 1100, 1600              # MANUAL
    elif n < PPM_LOOP:
        mode, throttle = 1600, 2100              # AUTO1, full throttle
    else:
        mode, throttle = 1900, 2100              # AUTO2, full throttle
    return [throttle, roll, 1500, 1500, mode, 1500, 1500, 1500, 1500]


# -------------------------------------------------------------------- GPS
NAV_UTM_EAST0 = 605530          # flight_plan.h
NAV_UTM_NORTH0 = 5797350
GPS_EPOCHS = 120
GPS_PERIOD_MS = 250
CIRCLE_E, CIRCLE_N, CIRCLE_R = 60.0, -40.0, 80.0
SPEED = 15.0                    # m/s
ALT = 200.0                     # m
CLIMB = 0.0


def ubx(cls, mid, payload):
    body = bytes([cls, mid]) + struct.pack('<H', len(payload)) + payload
    ck_a = ck_b = 0
    for b in body:
        ck_a = (ck_a + b) & 0xFF
        ck_b = (ck_b + ck_a) & 0xFF
    return bytes([0xB5, 0x62]) + body + bytes([ck_a, ck_b])


def gps_epoch(k):
    itow = 100000 + k * GPS_PERIOD_MS            # ms
    t = k * GPS_PERIOD_MS / 1000.0
    w = SPEED / CIRCLE_R                         # rad/s, counter-clockwise
    a = w * t
    east = CIRCLE_E + CIRCLE_R * math.cos(a)
    north = CIRCLE_N + CIRCLE_R * math.sin(a)
    v_e = -SPEED * math.sin(a)
    v_n = SPEED * math.cos(a)
    course = math.degrees(math.atan2(v_e, v_n)) % 360.0   # from north

    posutm = struct.pack('<IiiibB', itow,
                         int(round((NAV_UTM_EAST0 + east) * 100)),
                         int(round((NAV_UTM_NORTH0 + north) * 100)),
                         int(round(ALT * 100)), 31, 0)
    status = struct.pack('<IBBBBII', itow, 3, 0x0D, 0, 0, 30000, 30000 + itow)
    velned = struct.pack('<IiiiIIiII', itow,
                         int(round(v_n * 100)), int(round(v_e * 100)),
                         int(round(-CLIMB * 100)),
                         int(round(SPEED * 100)), int(round(SPEED * 100)),
                         int(round(course * 1e5)), 50, 100000)
    return (ubx(0x01, 0x08, posutm) + ubx(0x01, 0x03, status) +
            ubx(0x01, 0x12, velned))


# ------------------------------------------------------------------ output
def sv_list(values, fmt, per_line=12):
    items = [fmt % v for v in values]
    lines = [', '.join(items[i:i + per_line])
             for i in range(0, len(items), per_line)]
    return '{\n    ' + ',\n    '.join(lines) + '\n  }'


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    ppm = [w for n in range(PPM_FRAMES) for w in ppm_frame(n)]
    epochs = [gps_epoch(k) for k in range(GPS_EPOCHS)]
    epoch_bytes = len(epochs[0])
    assert all(len(e) == epoch_bytes for e in epochs)
    gps = b''.join(epochs)

    out = []
    out.append('// Generated by hw/stimulus/gen_stimulus.py -- do not edit.\n')
    out.append('localparam int unsigned PB_PPM_FRAMES = %d;\n' % PPM_FRAMES)
    out.append('localparam int unsigned PB_PPM_CHANNELS = %d;\n' % PPM_CHANNELS)
    out.append('localparam int unsigned PB_PPM_LOOP = %d;\n' % PPM_LOOP)
    out.append('localparam int unsigned PB_PPM_US [PB_PPM_FRAMES*PB_PPM_CHANNELS] = '
               "'%s;\n" % sv_list(ppm, '%d'))
    out.append('localparam int unsigned PB_GPS_EPOCHS = %d;\n' % GPS_EPOCHS)
    out.append('localparam int unsigned PB_GPS_EPOCH_BYTES = %d;\n' % epoch_bytes)
    out.append('localparam int unsigned PB_GPS_PERIOD_MS = %d;\n' % GPS_PERIOD_MS)
    out.append('localparam logic [7:0] PB_GPS_BYTES [PB_GPS_EPOCHS*PB_GPS_EPOCH_BYTES] = '
               "'%s;\n" % sv_list(gps, "8'h%02x", 16))
    with open(sys.argv[1], 'w') as f:
        f.write(''.join(out))


if __name__ == '__main__':
    main()
