// PapaBench simulation environment: deterministic stimuli for the SoC inputs.
//
// Instantiated by the simulation tops (single MCU: hw/patches/0005-sim-top-
// papabench-env.patch, both GPIO banks of the one SoC; two MCUs:
// hw/rtl/papabench_dual.sv, the FBW's bank 0 and the Autopilot's bank 1).
// Everything is a function of the clock and of the tables in
// papabench_stim.svh (generated by hw/stimulus/gen_stimulus.py), so every
// run sees the same input at the same cycle. Each program has its own GPIO
// bank (hw/patches/0003-soc-gpio-banks.patch, bits shared with
// harness/periph.h), and enables its own stimuli through it:
//
//   FBW, GPIO bank 0
//     fbw_gpo_i[0]  environment enable (radio PPM)
//     fbw_gpi_o[0]  radio PPM line: its falling edges raise the bank's
//                   IRQ 17 (edge interrupt in the GPIO)
//   Autopilot, GPIO bank 1
//     ap_gpo_i[0]   environment enable (modem clock, GPS)
//     ap_gpi_o[0]   modem clock line: its falling edges raise the bank's
//                   IRQ 24
//   uart_rx_o       GPS UBX bursts at 115200 baud 8N1; idle high
//
// The other gp_o bits of each bank (servo 4017 clock and reset, modem TX
// data, run over) are not read here. A stimulus starts counting when its
// enable is set; until then its line idles high.
//
// Radio PPM: frame n starts with the sync edge, followed by one falling edge
// per channel, PB_PPM_US[n*9+ch] us apart; the frame lasts PpmFrameUs (at
// least SyncMinUs after the last channel edge). The line is low for PpmLowUs
// after each edge.
// After the last frame the PPM table is replayed from frame PB_PPM_LOOP
// (the radio stays in the last mode of the scenario).
// Modem clock: ModemHz square wave (one falling edge per bit).
// GPS: epoch k (PB_GPS_EPOCH_BYTES bytes) starts GpsFirstMs + k * period;
// the GPS table is replayed cyclically.
module papabench_env #(
  parameter int unsigned ClkHz       = 50_000_000,
  parameter int unsigned UartBaud    = 115_200,
  parameter int unsigned ModemHz     = 4_800,
  parameter int unsigned PpmFrameUs  = 25_000,
  parameter int unsigned PpmLowUs    = 300,
  parameter int unsigned SyncMinUs   = 8_000,
  parameter int unsigned FirstEdgeUs = 1_000,
  parameter int unsigned GpsFirstMs  = 250
) (
  input  logic        clk_i,
  input  logic        rst_ni,
  input  logic [15:0] fbw_gpo_i,
  output logic [7:0]  fbw_gpi_o,
  input  logic [15:0] ap_gpo_i,
  output logic [7:0]  ap_gpi_o,
  output logic        uart_rx_o
);
  `include "papabench_stim.svh"

  localparam int unsigned CyclesPerUs   = ClkHz / 1_000_000;
  localparam int unsigned ClocksPerBaud = ClkHz / UartBaud;   // as uart.sv
  localparam int unsigned ModemHalf     = ClkHz / ModemHz / 2;
  localparam int unsigned GpsPeriod     = ClkHz / 1000 * PB_GPS_PERIOD_MS;
  localparam int unsigned GpsBytes      = PB_GPS_EPOCHS * PB_GPS_EPOCH_BYTES;

  logic en_fbw, en_autopilot;
  assign en_fbw       = fbw_gpo_i[0];
  assign en_autopilot = ap_gpo_i[0];

  // ------------------------------------------------------------ radio PPM
  logic [31:0] ppm_cnt;      // cycles to the next edge
  logic [31:0] ppm_used;     // cycles used in this frame (sync edge = 0)
  logic [3:0]  ppm_ch;       // channel edges emitted in this frame
  logic [31:0] ppm_frame;
  logic [31:0] ppm_low;      // cycles the line stays low

  function automatic logic [31:0] ppm_width(logic [31:0] frame, logic [3:0] ch);
    return PB_PPM_US[frame * PB_PPM_CHANNELS + 32'(ch)] * CyclesPerUs;
  endfunction

  function automatic logic [31:0] ppm_gap(logic [31:0] used);
    logic [31:0] frame_len, min_gap;
    frame_len = PpmFrameUs * CyclesPerUs;
    min_gap   = SyncMinUs * CyclesPerUs;
    return (used + min_gap > frame_len) ? min_gap : frame_len - used;
  endfunction

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      ppm_cnt   <= FirstEdgeUs * CyclesPerUs;
      ppm_used  <= '0;
      ppm_ch    <= '0;
      ppm_frame <= '0;
      ppm_low   <= '0;
    end else if (en_fbw) begin
      if (ppm_low != 0) ppm_low <= ppm_low - 1;
      if (ppm_cnt != 0) begin
        ppm_cnt <= ppm_cnt - 1;
      end else begin
        ppm_low <= PpmLowUs * CyclesPerUs;
        if (32'(ppm_ch) < PB_PPM_CHANNELS) begin
          // next edge ends channel ppm_ch
          ppm_cnt  <= ppm_width(ppm_frame, ppm_ch) - 1;
          ppm_used <= ppm_used + ppm_width(ppm_frame, ppm_ch);
          ppm_ch   <= ppm_ch + 1;
        end else begin
          // last channel edge: sync gap, then the next frame's sync edge
          ppm_cnt   <= ppm_gap(ppm_used) - 1;
          ppm_used  <= '0;
          ppm_ch    <= '0;
          ppm_frame <= (ppm_frame + 1 == PB_PPM_FRAMES) ? PB_PPM_LOOP : ppm_frame + 1;
        end
      end
    end
  end

  // Low for PpmLowUs from every edge, high otherwise
  assign fbw_gpi_o = {7'b0, !en_fbw || (ppm_low == 0)};

  // ---------------------------------------------------------- modem clock
  logic [31:0] modem_cnt;
  logic        modem_clk;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      modem_cnt <= ModemHalf - 1;
      modem_clk <= 1'b1;
    end else if (en_autopilot) begin
      if (modem_cnt == 0) begin
        modem_cnt <= ModemHalf - 1;
        modem_clk <= ~modem_clk;
      end else begin
        modem_cnt <= modem_cnt - 1;
      end
    end
  end

  // One falling edge per bit
  assign ap_gpi_o = {7'b0, modem_clk};

  // ------------------------------------------------------------ GPS UART
  logic [31:0] gps_wait;     // cycles to the next epoch
  logic [31:0] gps_epoch;
  logic [31:0] gps_idx;      // bytes left to send in this epoch
  logic [31:0] gps_ptr;      // next byte in PB_GPS_BYTES
  logic [9:0]  tx_shift;     // stop, data[7:0], start (LSB first)
  logic [3:0]  tx_bits;      // bits left in tx_shift
  logic [31:0] tx_baud;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      gps_wait  <= GpsFirstMs * (ClkHz / 1000);
      gps_epoch <= '0;
      gps_idx   <= '0;
      gps_ptr   <= '0;
      tx_shift  <= '1;
      tx_bits   <= '0;
      tx_baud   <= '0;
    end else if (en_autopilot) begin
      if (gps_wait != 0) begin
        gps_wait <= gps_wait - 1;
      end else begin
        gps_wait <= GpsPeriod - 1;
        gps_idx  <= PB_GPS_EPOCH_BYTES;
        gps_ptr  <= gps_epoch * PB_GPS_EPOCH_BYTES;
        gps_epoch <= (gps_epoch + 1 == PB_GPS_EPOCHS) ? '0 : gps_epoch + 1;
      end

      if (tx_bits != 0) begin
        if (tx_baud != 0) begin
          tx_baud <= tx_baud - 1;
        end else begin
          tx_baud  <= ClocksPerBaud - 1;
          tx_shift <= {1'b1, tx_shift[9:1]};
          tx_bits  <= tx_bits - 1;
        end
      end else if (gps_idx != 0 && gps_wait != 0) begin
        tx_shift <= {1'b1, PB_GPS_BYTES[gps_ptr % GpsBytes], 1'b0};
        tx_bits  <= 4'd10;
        tx_baud  <= ClocksPerBaud - 1;
        gps_idx  <= gps_idx - 1;
        gps_ptr  <= gps_ptr + 1;
      end
    end
  end

  // Line = LSB of the shift register while a byte is on the wire
  assign uart_rx_o = (tx_bits != 0) ? tx_shift[0] : 1'b1;

  logic unused_gp_o;
  assign unused_gp_o = ^{fbw_gpo_i[15:1], ap_gpo_i[15:1]};
endmodule
